# Generated by Django 3.0 on 2024-08-08 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favorite_city",
                    models.CharField(
                        blank=True,
                        help_text="La ville préférée de l'utilisateur (optionnelle).",
                        max_length=64,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="L'utilisateur associé à ce profil.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
