# Generated by Django 3.2.5 on 2024-08-05 22:28

from django.db import migrations


def move_profiles_data(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")

    for old_profile in OldProfile.objects.all():
        new_profile = NewProfile(
            user=old_profile.user, favorite_city=old_profile.favorite_city
        )
        new_profile.save()


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
        ("oc_lettings_site", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(move_profiles_data),
    ]
