# .readthedocs.yaml

version: 2

# Configuration de l'environnement Python
python:
  version: "3.11"
  install:
    - method: pip
      path: .
    - requirements: doc/requirements.txt

# Configuration de Sphinx
sphinx:
  configuration: doc/conf.py

# Spécifier l'image pour la construction
build:
  image: "latest"
  os: "ubuntu-24.04"
  tools:
    python: "3.11"

# Jobs de construction
build:
  jobs:
    pre_checkout:
      - echo "Running pre-checkout tasks"
    post_checkout:
      - echo "Running post-checkout tasks"
    pre_system_dependencies:
      - echo "Installing system dependencies"
    post_system_dependencies:
      - echo "System dependencies installed"
    pre_create_environment:
      - echo "Preparing environment"
    post_create_environment:
      - echo "Environment prepared"
    pre_install:
      - echo "Running pre-install tasks"
    post_install:
      - echo "Running post-install tasks"
    pre_build:
      - echo "Preparing for build"
    post_build:
      - echo "Build completed"

# Branch par défaut
default_branch: master
