# Generated by Django 3.0 on 2024-08-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0002_move_lettings_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adresse', 'verbose_name_plural': 'adresses'},
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='letting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
